stages:
  - lint_stage
  - build_stage

cache:
  - key:
        files:
        - ./backend/package-lock.json
    paths:
        - ./backend/node_modules
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
        - ./frontend/billy/.npm

eslint:
  stage: lint_stage
  image: node
  script:
    - cd backend
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

build: 
  stage: build_stage
  image: node:alpine
  script:
    - cd backend
    - npm install
    - echo GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID >> .env        
    - echo GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET >> .env 
    - cd ../frontend/billy
    - npm ci --cache .npm
    - apk add --no-cache bash
    - EXPO_TOKEN=$EXPO_TOKEN npx expo prebuild
  artifacts:
    paths: 
      - ./backend/node_modules
      - ./backend/package-lock.json
      - ./backend/.env
      - ./frontend/billy/ios
      - ./frontend/billy/android