image: node:22.4.1

stages:
  - lint_stage
  - build_stage

before_script:
  - node -v
  - npm install

cache:
  - key:
        files:
        - ./backend/package-lock.json
    paths:
        - ./backend/node_modules
  - key: 
      files:
        - ./frontend/billy/package-lock.json
    paths:
        - ./frontend/billy/.node_modules

eslint:
  stage: lint_stage
  script:
    - cd backend
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

build: 
  stage: build_stage
  script:
    - cd backend
    - npm install
    - echo GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID >> .env        
    - echo GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET >> .env 
    - cd ../frontend/billy
    - npm install
    - EXPO_TOKEN=$EXPO_TOKEN npx expo prebuild
  artifacts:
    paths: 
      - ./backend/node_modules
      - ./backend/package-lock.json
      - ./backend/.env
      - ./frontend/billy/ios
      - ./frontend/billy/android